### ISSUE TITLE
Units and normalization of the spectrum

### ISSUE THREAD

**Issue by XuejianShen** [AtomDB/pyatomdb#30]
The unit of the spectrum from **pyatomdb.spectrum.CIESession** is "photons cm^5 s^-1 bin^-1" ( "photons cm^3 s^-1 bin^-1" if raw is set). The question is what is the normalization of the spectrum?

By units, I would naively imagine the norm is **the emission measure: ne nH dV, in unit of cm^-3**. But I've also seen the convention of a **10^(-14)** factor (or with a **1/4pi dA^2 factor**) in front of the emission measure some place. So what is the correct normalization for the output spectrum here?

**Comment by jagophile** [comment]
Hi,

I'm not 100% sure what you mean by the normalization of the spectrum - none is applied in pyatomdb. You have emissivities, which you then multiply by the emission measure, a factor for source distance and the effective area of the instrument to get counts per bin per second.

The factor of 10^-14 is due to an XSPEC feature. XSPEC likes it's fit parameters to be around 1. Since emissivities from apec tend to be small (1e-13 or less), XSPEC adds a multiplier on the front of 10^14. So if you run the apec model in XSPEC and a CIESession in pyatomdb, you will find a difference of 10^14. Often, literature quotes the norm value in units of 10^-14 as that is what XSPEC returns.

The norm, in terms of XSPEC compatible models, encompasses everything which is not the emissivity. This will include the density and size of the emitting region (the emission measure) and the distance to the source, assuming spherical symmetry (1/[4pi D^2]). It therefore has units of cm^-5 (plus the 10-14 factor mentioned earlier)

Does this help?

**Comment by XuejianShen** [comment]
Hi,

Thanks for clarification! Sorry for late response. I think it all makes sense.
So if I set the response to raw and the compute the spectrum with Pyatomdb. Should I understand the result I get as the emissivities? (which then will be multiplied with the emission measure and the factor 1/[4pi D^2] to get the real flux)

A related question is:  does "photons cm^3 s^-1 bin^-1" imply photon counts divided by the energy interval of the bin or just photon counts in each bin?

**Comment by jagophile** [comment]
My turn to apologize for a slow response.

To your question - yes.

And then the bin^-1 means counts per bin, no energy correction applied. 

I am closing this for now as it has been around for a long time. If you have further questions feel free to re-open it.
