### ISSUE TITLE
Question about shape of pure hydrogen spectrum

### ISSUE THREAD

**Issue by jzuhone** [AtomDB/pyatomdb#31]
Hi, 

I made a pure hydrogen spectrum with PyAtomDB here:

https://nbviewer.jupyter.org/gist/jzuhone/20793167d0aa4c416117daefac88d479

The plot shows the spectrum multiplied by the middle of each energy bin, where the energy bins are linear.

I'm a bit surprised at how bumpy the spectrum is. Is there an explanation for this?

**Comment by jagophile** [comment]
Hi John,

A couple of things are going on here. The main one is that to speed computation in XSPEC, the spectral data are stored using a linear approximation to the curve. If you plot the same model as you used on a linear instead of log-log scale you can see this. Then, since we make this approximation for the photon number, not the total energy per bin, the issue become significantly more obvious when you plot energy*nphot for each bin.

![linearplot](https://user-images.githubusercontent.com/7048277/106791180-98002680-6622-11eb-9292-5db217afad99.png)

The underlying calculation in AtomDB does not suffer from this issue, but we do then apply this simplification to make the file tractable in the XSPEC models (and therefore also in what the pyatomdb spectrum module produces).

Is this an issue for any work you are doing at the moment, or does it just look strange? We have talked of updating the XSPEC model to calculate the brems on the fly instead of using the tables, so if this is likely to be useful (or if you have an interesting test case) I could code that up and we'll see what we see in terms of perfomance and the resulting interpretation.

**Comment by jagophile** [comment]
Hi John,

I'm closing this now, let me know if you need more information.

Thanks
Adam
