### ISSUE TITLE
I cannot make spectrum using rmf/arf file.

### ISSUE THREAD

**Issue by hajime7610** [AtomDB/pyatomdb#40]
I tried to make spectrum using rmf and arf file downloaded from `https://xrism.isas.jaxa.jp/research/proposer/obsplan/response/index.html`, however  it doesn't work due to some following errors:

> $ python test_resovle.py         
> /Users/anaconda3/envs/py2021/lib/python3.9/site-packages/pyatomdb/apec.py:1001: RuntimeWarning: divide by zero encountered in log10
>  bigx = (1/2.5) * (numpy.log10(x) + 1.50)
> /Users/anaconda3/envs/py2021/lib/python3.9/site-packages/pyatomdb/apec.py:1004: RuntimeWarning: invalid value encountered in add
>  GI += aI[i,j]*(theta**i)*(bigx**j)
> /Users/anaconda3/envs/py2021/lib/python3.9/site-packages/pyatomdb/apec.py:1006: RuntimeWarning: divide by zero encountered in true_divide
>  ret = 1.455e-16*N**2*numpy.exp(-x)/(x*numpy.sqrt(tao))*GI
> Press enter to continue

**Comment by jagophile** [comment]
Hi @hajime7610 , thanks for the input. 

Can you upload your test_resovle.py script? I'll take a look and see what's happening.

Thanks,
Adam

**Comment by yamadasuzaku** [comment]
Sorry for our lack of the explanation. This is because the files are downloaded from https://xrism.isas.jaxa.jp/research/proposer/obsplan/response/index.html, and the energies in their files start with 0 keV. It causes in apex.py,  
1) L982  x = Earray/T <== X start with 0, 
2) L1001  bigx = (1/2.5) * (numpy.log10(x) + 1.50) <== log10(x) causes zerodiv warning
The definition of the response and arf files depends on the specification of the fits files. 

This is what my student tried to do. 
`
import pyatomdb
import numpy
import pylab


# declare the Collisional Ionization Equilibrium session
sess = pyatomdb.spectrum.CIESession()

# create a set of energy bins (in keV) for the response. Note these are
# the n edges of the n-1 bins.
ebins = numpy.linspace(0.3,1.0,10000)

# set the response (raw keyword tells pyatomdb it is not a real response file)
sess.set_response(ebins, raw=True)

kT = 0.4 # temperature in keV
spec = sess.return_spectrum(kT)

# we now have a spectrum and the energy bins,

# prepend a zero to the spectrum so that energy bins and spectrum have
# the same length. If you use a different plotting system you may
# need to add this to the end.
spec = numpy.append(0, spec)

# Returned spectrum has units of photons cm^5 s^-1 bin^-1
fig = pylab.figure()
fig.show()
ax = fig.add_subplot(211)
ax.plot(sess.ebins_out, spec, drawstyle='steps', label='dummy response')

# label the figure
ax.set_xlabel('Energy (keV)')
ax.set_ylabel('Intensity (ph cm$^5$ s$^{-1}$ bin$^{-1}$)')

# zoom in a bit
#ax.set_xlim([0.8,0.85])

# make plot appear

# now repeat the process with a real response
# set response

resormf="resolve_h7ev_2019a.rmf"
resoarf="resolve_pnt_spec_noGV_20190611.arf"

sess.set_response(resormf, arf = resoarf)

# get spectrum, prepend zero
spec = sess.return_spectrum(kT)
spec = numpy.append(0, spec)

ax2 = fig.add_subplot(212)
ax2.plot(sess.ebins_out, spec, drawstyle='steps', label='Resolve')
#ax2.plot(sess.ebins_out, spec, drawstyle='steps', label='Chandra MEG')

# add legends
ax.legend(loc=0)
ax2.legend(loc=0)

# zoom in on small sections of the spectrum
ax.set_xlim([0.7, 0.9])
ax2.set_xlim([0.7, 0.9])

# set axes
ax2.set_xlabel('Energy (keV)')
ax2.set_ylabel('Intensity (ph cm$^5$ s$^{-1}$ bin$^{-1}$)')

# adjust plot spacing so labels are visible
pylab.matplotlib.pyplot.subplots_adjust(hspace = 0.34)

# draw graphs
pylab.draw()

zzz=input("Press enter to continue")

# save image files
fig.savefig('spectrum_session_examples_1_1.pdf')
fig.savefig('spectrum_session_examples_1_1.svg')
`

**Comment by jagophile** [comment]
Ah. That would cause issues. This is a bug and I will fix it, but it will take a few hours.

I'll let you know when I have a fix ready.

**Comment by jagophile** [comment]
OK, I think this is now fixed, and released as version 0.10.10, and also on Github (git pull will grab it). It does issue a warning to the screen but that can be ignored.

This has revealed another issue, which is that the XRISM responses are so large they make my computer run out of memory. I'm going to tackle that next week.

**Comment by hajime7610** [comment]
Hi Adam,

Thanks! I was able to make spectrum successfully using XRISM response files.

**Comment by jagophile** [comment]
Just to follow up (and close) this - I have now introduced a new response matrix option, "sparse=True" to the ser_response function which allows handling large response matrices (e.g. XRISM) with limited memory.

**Comment by yamadasuzaku** [comment]
Hi Adam,

Thank you for your prompt response. This is good news for all of us.

Sincerely,

Shinya Yamada

2022年8月4日(木) 22:48 Adam Foster ***@***.***>:
