### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by Jisans** [AtomDB/pyatomdb#41]
hello all! Is it normal for me to get this prompt when installing pyatomdb module?  

```
/mnt/c/Users/HG » python3                                                                    hank@DESKTOP-10UCA6U
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyatomdb
ATOMDB Environment Variable Not Set. Set up AtomDB files now? (yes/no/info) [yes]
```
system: Linux DESKTOP-10UCA6U 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
(base)
python version 3.7.12
pip version 22.1.2

**Comment by jagophile** [comment]
Hi,

Yes, this is normal, though I should update the documentation to reflect it. AtomDB requires a series of large data files which can't be distributed through pip or GitHub, so instead it does this check for the files in your $ATOMDB folder.

Once you download the files, you should set the ATOMDB environment variable to where the files are installed (e.g. export ATOMDB=/home/user/atomdb), and then it won't prompt this anymore.

**Comment by Jisans** [comment]
It's strange that when I export pyatondb, it pops up asking me to set the environment variable. Should I be yes here or / home / user / pyatomdb, and then the download data file will pop up. Is the download under the environment variable path?

**Comment by jagophile** [comment]
Hi, this is confusing yes. Let me try and example.

When you import pyatomdb, it looks in the $ATOMDB folder for the atomic database. If it doesn't find it (usually because the ATOMDB variable is not set) then it asks to download the data.

`>>> import pyatomdb`
`ATOMDB Environment Variable Not Set. Set up AtomDB files now? (yes/no/info) [yes]yes`
`Location to install AtomDB files [/media/afoster/T7/atomdb] :`
`Allow reporting of anonymous usage statistics (yes/no/info) [yes]`
`You are about to install:`
`AtomDB installation location: /media/afoster/T7/atomdb`
`Transmit anonymous user data: yes`
`Randomly generated userid: 75564026`
`Is this ok? (y/n) [y]`
**`Temporarily setting $ATOMDB environment variable to /media/afoster/T7/atomdb.  It is *strongly* recommended that you add this to your environment   permanently.`**
`creating directory /media/afoster/T7/atomdb ...done`
`creating user data file /media/afoster/T7/atomdb/userdata ...done`
`finding current version of AtomDB.  Latest version is 3.0.9`
`Do you wish to download the emissivity data for these files (recommended)? (y/n) [y]y`
`making directory /media/afoster/T7/atomdb/installtmp`
`100% [......................................................................] 131398622 / 131398622`
 etc etc


If you say "yes" after importing pyatomdb, you should get the above output. This finished with the data being downloaded to a directory you choose (in this case, I chose " /media/afoster/T7/atomdb").

You should then (as shown in the bolded text above) add the ATOMDB environment variable to your profile - I am not sure what shell you are using but for bash it would be the .bashrc file, for csh it would be .cshrc - and add a line so the ATOMDB environment variable is always set.

e.g. add the line "export ATOMDB=/media/afoster/T7/atomdb" to .bashrc
or "setenv /media/afoster/T7/atomdb" to .cshrc.

(if you tell me what shell you are using I can pinpoint the right file).

Once the ATOMDB variable is set, and the data is in place, whenever you restart pyatomdb in the future it will not ask you all these questions.

Does this help?

**Comment by Jisans** [comment]
Sir, can I install it this way?
```
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyatomdb
ATOMDB Environment Variable Not Set. Set up AtomDB files now? (yes/no/info) [yes]yes
Location to install AtomDB files [/home/jisans/atomdb] :
Allow reporting of anonymous usage statistics (yes/no/info) [yes]
You are about to install:
AtomDB installation location: /home/jisans/atomdb
Transmit anonymous user data: yes
Randomly generated userid: 49387971
Is this ok? (y/n) [y]
Temporarily setting $ATOMDB environment variable to /home/jisans/atomdb.  It is *strongly* recommended that you add this to your environment   permanently.
creating directory /home/jisans/atomdb ...done
creating user data file /home/jian/atomdb/userdata ...done
finding current version of AtomDB.  Latest version is 3.0.9
Do you wish to download the emissivity data for these files (recommended)? (y/n) [y]y
making directory /home/jisans/atomdb/installtmp
  4% [...                                                                   ]   6209536 / 131398622
```
Then I was there Just set export = / home / jisans / atomdb / in .bashrc!

**Comment by Jisans** [comment]
Sir, it's strange! I still need to reset the environment variables when I run in notebook,
![image](https://user-images.githubusercontent.com/110452095/184809854-ba02a2fd-8080-4dbb-939d-7444d33a18e8.png)
I should have downloaded the data files when `import pyatomdb,`

**Comment by Jisans** [comment]
Sir, I have installed it and `pyatomdb` is working normally
